import { createContext, useContext, useEffect, useMemo, useState, type ReactNode } from 'react'

export const LANGUAGE_STORAGE_KEY = 'reliable-language'

export const LANGUAGES = [
  { code: 'en', nativeName: 'English', dir: 'ltr' },
  { code: 'zh', nativeName: '中文', dir: 'ltr' },
  { code: 'es', nativeName: 'Español', dir: 'ltr' },
  { code: 'fr', nativeName: 'Français', dir: 'ltr' },
  { code: 'pt', nativeName: 'Português', dir: 'ltr' },
  { code: 'ar', nativeName: 'العربية', dir: 'rtl' },
  { code: 'hi', nativeName: 'हिन्दी', dir: 'ltr' },
  { code: 'bn', nativeName: 'বাংলা', dir: 'ltr' },
  { code: 'ru', nativeName: 'Русский', dir: 'ltr' },
  { code: 'ja', nativeName: '日本語', dir: 'ltr' },
  { code: 'ko', nativeName: '한국어', dir: 'ltr' },
  { code: 'de', nativeName: 'Deutsch', dir: 'ltr' },
  { code: 'it', nativeName: 'Italiano', dir: 'ltr' },
  { code: 'tr', nativeName: 'Türkçe', dir: 'ltr' },
  { code: 'vi', nativeName: 'Tiếng Việt', dir: 'ltr' },
  { code: 'id', nativeName: 'Bahasa Indonesia', dir: 'ltr' },
  { code: 'nl', nativeName: 'Nederlands', dir: 'ltr' },
  { code: 'pl', nativeName: 'Polski', dir: 'ltr' },
  { code: 'sw', nativeName: 'Kiswahili', dir: 'ltr' },
  { code: 'ha', nativeName: 'Hausa', dir: 'ltr' },
  { code: 'mg', nativeName: 'Malagasy', dir: 'ltr' },
] as const

export type LanguageCode = (typeof LANGUAGES)[number]['code']
export type TranslationKey = keyof typeof translations.en

type TranslationMap = Record<string, string>

const english = {
  language: 'Language', home: 'Home', categories: 'Categories', ourCategories: 'Our Categories', deals: 'Deals',
  startSelling: 'Start Selling', stores: 'Stores', shop: 'Shop', aboutUs: 'About Us', sell: 'Sell', account: 'Account',
  wishlist: 'Wishlist', orders: 'Orders', marketplaceNews: 'Marketplace News', articles: 'Articles', about: 'About',
  contact: 'Contact', support: 'Support', settings: 'Settings', loginRegister: 'Login / Register', search: 'Search',
  searchProducts: 'Search products, categories...', searchProductsBrands: 'Search products, brands, categories…',
  adminDashboard: 'Admin Dashboard', sellerDashboard: 'Seller Dashboard', advertise: 'Advertise on Reliable',
  loadingReliable: 'Loading Reliable', quickLinks: 'Quick Links', products: 'Products', contactUs: 'Contact Us',
  deliveryInformation: 'Delivery Information', policies: 'Policies', privacyPolicy: 'Privacy Policy', terms: 'Terms & Conditions',
  returns: 'Return & Refund Policy', premiumMarketplace: 'Premium Marketplace', allRightsReserved: 'All rights reserved.',
  searchStores: 'Search stores, categories, or locations', loadingStores: 'Loading stores...',
  noResults: 'No results found', addToCart: 'Add to Cart', outOfStock: 'Out of Stock', checkout: 'Checkout',
  viewDetails: 'View Details', sponsored: 'Sponsored', marketplacePick: 'Marketplace pick', deliveryAvailable: 'Delivery available',
  deliveryFrom: 'Delivery from', brand: 'Brand', newProduct: 'New', reviews: 'reviews', productNotFound: 'Product not found',
  backToProducts: 'Back to Products', soldBy: 'Sold by', description: 'Description', selectSizes: 'Select Sizes (Multiple allowed)',
  quantity: 'Quantity', chatWithSeller: 'Chat with Seller', removeFromWishlist: 'Remove from wishlist', addToWishlist: 'Add to wishlist',
  zoomImage: 'Zoom image', noMediaAvailable: 'No media available', inStock: 'In Stock', stockAvailable: 'Stock Available',
  availability: 'Availability', shoppingCart: 'Shopping Cart', closeCart: 'Close cart', emptyCart: 'Your cart is empty',
  continueShopping: 'Continue Shopping', cartSummary: 'Cart summary', subtotal: 'Subtotal',
  secureShopping: 'Secure shopping with Reliable. Delivery and payment details are confirmed at checkout.', item: 'item', items: 'items',
  remove: 'Remove', multipleStoresSelected: 'Multiple stores selected', oneStoreCheckout: 'Checkout is handled one store at a time. Remove items from other stores before paying.',
  proceedToCheckout: 'Proceed to Checkout', emptyCartAction: 'Empty Cart', addProductsBeforeCheckout: 'Add some products to your cart before checking out.',
  browseProducts: 'Browse Products', createAccountToContinue: 'Create a customer account to continue.',
  orderHistoryPrompt: 'Sign in or create an account to keep your order history, delivery details, and notifications together.',
  createCustomerAccount: 'Create Customer Account', login: 'Login', fullName: 'Full Name', emailAddress: 'Email Address',
  phoneNumber: 'Phone Number', deliveryAddress: 'Delivery Address', city: 'City', region: 'Region', deliveryMethod: 'Delivery Method',
  additionalNotes: 'Additional Notes', deliveryOptionsLoading: 'Loading delivery options...', processing: 'Processing...',
  proceedToPayment: 'Proceed to Payment', needHelp: 'Need help with your order?', callUs: 'Call us', processingPayment: 'Processing Payment',
  redirectedToPaystack: 'You will be redirected to Paystack to complete your payment.', verifyPayment: 'Verify Payment',
  verifyingPayment: 'Verifying Payment', verifyingPaymentWait: 'Please wait while we verify your payment...', orderSummary: 'Order Summary',
  deliveryFee: 'Delivery Fee', total: 'Total', paymentSuccessful: 'Payment successful! Your order has been placed. A confirmation email has been sent.',
  paymentFailed: 'Paystack reported that this payment failed. No successful order was created.',
} as const

const translations: Record<LanguageCode, TranslationMap> = {
  en: english,
  zh: { language: '语言', home: '首页', categories: '分类', ourCategories: '我们的分类', deals: '优惠', startSelling: '开始销售', stores: '商店', shop: '购物', aboutUs: '关于我们', sell: '出售', account: '账户', wishlist: '愿望清单', orders: '订单', marketplaceNews: '市场新闻', articles: '文章', about: '关于', contact: '联系我们', support: '支持', settings: '设置', loginRegister: '登录 / 注册', search: '搜索', searchProducts: '搜索产品、分类...', searchProductsBrands: '搜索产品、品牌、分类…', adminDashboard: '管理员面板', sellerDashboard: '卖家面板', advertise: '在 Reliable 上投放广告', loadingReliable: '正在加载 Reliable', quickLinks: '快速链接', products: '产品', contactUs: '联系我们', deliveryInformation: '配送信息', policies: '政策', privacyPolicy: '隐私政策', terms: '条款和条件', returns: '退货和退款政策', premiumMarketplace: '高端市场', allRightsReserved: '版权所有。', searchStores: '搜索商店、分类或地点', loadingStores: '正在加载商店...', noResults: '未找到结果', addToCart: '加入购物车', outOfStock: '缺货', checkout: '结账' },
  es: { language: 'Idioma', home: 'Inicio', categories: 'Categorías', ourCategories: 'Nuestras categorías', deals: 'Ofertas', startSelling: 'Empezar a vender', stores: 'Tiendas', shop: 'Comprar', aboutUs: 'Sobre nosotros', sell: 'Vender', account: 'Cuenta', wishlist: 'Lista de deseos', orders: 'Pedidos', marketplaceNews: 'Noticias del mercado', articles: 'Artículos', about: 'Acerca de', contact: 'Contacto', support: 'Ayuda', settings: 'Configuración', loginRegister: 'Iniciar sesión / Registrarse', search: 'Buscar', searchProducts: 'Buscar productos, categorías...', searchProductsBrands: 'Buscar productos, marcas, categorías…', adminDashboard: 'Panel de administración', sellerDashboard: 'Panel del vendedor', advertise: 'Anunciarse en Reliable', loadingReliable: 'Cargando Reliable', quickLinks: 'Enlaces rápidos', products: 'Productos', contactUs: 'Contáctanos', deliveryInformation: 'Información de entrega', policies: 'Políticas', privacyPolicy: 'Política de privacidad', terms: 'Términos y condiciones', returns: 'Política de devoluciones y reembolsos', premiumMarketplace: 'Mercado premium', allRightsReserved: 'Todos los derechos reservados.', searchStores: 'Buscar tiendas, categorías o ubicaciones', loadingStores: 'Cargando tiendas...', noResults: 'No se encontraron resultados', addToCart: 'Añadir al carrito', outOfStock: 'Agotado', checkout: 'Pagar' },
  fr: { language: 'Langue', home: 'Accueil', categories: 'Catégories', ourCategories: 'Nos catégories', deals: 'Offres', startSelling: 'Commencer à vendre', stores: 'Boutiques', shop: 'Acheter', aboutUs: 'À propos', sell: 'Vendre', account: 'Compte', wishlist: 'Liste de souhaits', orders: 'Commandes', marketplaceNews: 'Actualités du marché', articles: 'Articles', about: 'À propos', contact: 'Contact', support: 'Assistance', settings: 'Paramètres', loginRegister: 'Connexion / Inscription', search: 'Rechercher', searchProducts: 'Rechercher des produits, catégories...', searchProductsBrands: 'Rechercher des produits, marques, catégories…', adminDashboard: 'Tableau de bord administrateur', sellerDashboard: 'Tableau de bord vendeur', advertise: 'Faire de la publicité sur Reliable', loadingReliable: 'Chargement de Reliable', quickLinks: 'Liens rapides', products: 'Produits', contactUs: 'Nous contacter', deliveryInformation: 'Informations de livraison', policies: 'Politiques', privacyPolicy: 'Politique de confidentialité', terms: 'Conditions générales', returns: 'Politique de retour et remboursement', premiumMarketplace: 'Marché premium', allRightsReserved: 'Tous droits réservés.', searchStores: 'Rechercher des boutiques, catégories ou lieux', loadingStores: 'Chargement des boutiques...', noResults: 'Aucun résultat', addToCart: 'Ajouter au panier', outOfStock: 'Rupture de stock', checkout: 'Paiement' },
  pt: { language: 'Idioma', home: 'Início', categories: 'Categorias', ourCategories: 'Nossas categorias', deals: 'Ofertas', startSelling: 'Começar a vender', stores: 'Lojas', shop: 'Comprar', aboutUs: 'Sobre nós', sell: 'Vender', account: 'Conta', wishlist: 'Lista de desejos', orders: 'Pedidos', marketplaceNews: 'Notícias do marketplace', articles: 'Artigos', about: 'Sobre', contact: 'Contato', support: 'Suporte', settings: 'Configurações', loginRegister: 'Entrar / Cadastrar', search: 'Pesquisar', searchProducts: 'Pesquisar produtos, categorias...', searchProductsBrands: 'Pesquisar produtos, marcas, categorias…', adminDashboard: 'Painel administrativo', sellerDashboard: 'Painel do vendedor', advertise: 'Anuncie na Reliable', loadingReliable: 'Carregando Reliable', quickLinks: 'Links rápidos', products: 'Produtos', contactUs: 'Fale conosco', deliveryInformation: 'Informações de entrega', policies: 'Políticas', privacyPolicy: 'Política de privacidade', terms: 'Termos e condições', returns: 'Política de devolução e reembolso', premiumMarketplace: 'Marketplace premium', allRightsReserved: 'Todos os direitos reservados.', searchStores: 'Pesquisar lojas, categorias ou locais', loadingStores: 'Carregando lojas...', noResults: 'Nenhum resultado', addToCart: 'Adicionar ao carrinho', outOfStock: 'Esgotado', checkout: 'Finalizar compra' },
  ar: { language: 'اللغة', home: 'الرئيسية', categories: 'الفئات', ourCategories: 'فئاتنا', deals: 'العروض', startSelling: 'ابدأ البيع', stores: 'المتاجر', shop: 'تسوق', aboutUs: 'معلومات عنا', sell: 'بيع', account: 'الحساب', wishlist: 'قائمة الرغبات', orders: 'الطلبات', marketplaceNews: 'أخبار السوق', articles: 'المقالات', about: 'حول', contact: 'اتصل بنا', support: 'الدعم', settings: 'الإعدادات', loginRegister: 'تسجيل الدخول / التسجيل', search: 'بحث', searchProducts: 'ابحث عن المنتجات والفئات...', searchProductsBrands: 'ابحث عن المنتجات والعلامات التجارية والفئات…', adminDashboard: 'لوحة تحكم المسؤول', sellerDashboard: 'لوحة تحكم البائع', advertise: 'أعلن على Reliable', loadingReliable: 'جارٍ تحميل Reliable', quickLinks: 'روابط سريعة', products: 'المنتجات', contactUs: 'اتصل بنا', deliveryInformation: 'معلومات التوصيل', policies: 'السياسات', privacyPolicy: 'سياسة الخصوصية', terms: 'الشروط والأحكام', returns: 'سياسة الإرجاع والاسترداد', premiumMarketplace: 'سوق متميز', allRightsReserved: 'جميع الحقوق محفوظة.', searchStores: 'ابحث عن المتاجر أو الفئات أو المواقع', loadingStores: 'جارٍ تحميل المتاجر...', noResults: 'لم يتم العثور على نتائج', addToCart: 'أضف إلى السلة', outOfStock: 'غير متوفر', checkout: 'الدفع' },
  hi: { language: 'भाषा', home: 'होम', categories: 'श्रेणियाँ', ourCategories: 'हमारी श्रेणियाँ', deals: 'ऑफ़र', startSelling: 'बेचना शुरू करें', stores: 'स्टोर', shop: 'खरीदारी', aboutUs: 'हमारे बारे में', sell: 'बेचें', account: 'खाता', wishlist: 'विशलिस्ट', orders: 'ऑर्डर', marketplaceNews: 'मार्केटप्लेस समाचार', articles: 'लेख', about: 'परिचय', contact: 'संपर्क', support: 'सहायता', settings: 'सेटिंग्स', loginRegister: 'लॉगिन / रजिस्टर', search: 'खोजें', searchProducts: 'उत्पाद, श्रेणियाँ खोजें...', searchProductsBrands: 'उत्पाद, ब्रांड, श्रेणियाँ खोजें…', adminDashboard: 'एडमिन डैशबोर्ड', sellerDashboard: 'विक्रेता डैशबोर्ड', advertise: 'Reliable पर विज्ञापन दें', loadingReliable: 'Reliable लोड हो रहा है', quickLinks: 'त्वरित लिंक', products: 'उत्पाद', contactUs: 'संपर्क करें', deliveryInformation: 'डिलीवरी जानकारी', policies: 'नीतियाँ', privacyPolicy: 'गोपनीयता नीति', terms: 'नियम और शर्तें', returns: 'वापसी और रिफंड नीति', premiumMarketplace: 'प्रीमियम मार्केटप्लेस', allRightsReserved: 'सर्वाधिकार सुरक्षित।', searchStores: 'स्टोर, श्रेणियाँ या स्थान खोजें', loadingStores: 'स्टोर लोड हो रहे हैं...', noResults: 'कोई परिणाम नहीं मिला', addToCart: 'कार्ट में डालें', outOfStock: 'स्टॉक में नहीं', checkout: 'चेकआउट' },
  bn: { language: 'ভাষা', home: 'হোম', categories: 'বিভাগ', ourCategories: 'আমাদের বিভাগ', deals: 'অফার', startSelling: 'বিক্রি শুরু করুন', stores: 'দোকান', shop: 'কিনুন', aboutUs: 'আমাদের সম্পর্কে', sell: 'বিক্রি করুন', account: 'অ্যাকাউন্ট', wishlist: 'উইশলিস্ট', orders: 'অর্ডার', marketplaceNews: 'মার্কেটপ্লেস সংবাদ', articles: 'প্রবন্ধ', about: 'সম্পর্কে', contact: 'যোগাযোগ', support: 'সহায়তা', settings: 'সেটিংস', loginRegister: 'লগইন / নিবন্ধন', search: 'অনুসন্ধান', searchProducts: 'পণ্য, বিভাগ অনুসন্ধান করুন...', searchProductsBrands: 'পণ্য, ব্র্যান্ড, বিভাগ অনুসন্ধান করুন…', adminDashboard: 'অ্যাডমিন ড্যাশবোর্ড', sellerDashboard: 'বিক্রেতা ড্যাশবোর্ড', advertise: 'Reliable-এ বিজ্ঞাপন দিন', loadingReliable: 'Reliable লোড হচ্ছে', quickLinks: 'দ্রুত লিংক', products: 'পণ্য', contactUs: 'যোগাযোগ করুন', deliveryInformation: 'ডেলিভারি তথ্য', policies: 'নীতিমালা', privacyPolicy: 'গোপনীয়তা নীতি', terms: 'শর্তাবলি', returns: 'রিটার্ন ও রিফান্ড নীতি', premiumMarketplace: 'প্রিমিয়াম মার্কেটপ্লেস', allRightsReserved: 'সর্বস্বত্ব সংরক্ষিত।', searchStores: 'দোকান, বিভাগ বা স্থান অনুসন্ধান করুন', loadingStores: 'দোকান লোড হচ্ছে...', noResults: 'কোনো ফলাফল পাওয়া যায়নি', addToCart: 'কার্টে যোগ করুন', outOfStock: 'স্টক নেই', checkout: 'চেকআউট' },
  ru: { language: 'Язык', home: 'Главная', categories: 'Категории', ourCategories: 'Наши категории', deals: 'Скидки', startSelling: 'Начать продавать', stores: 'Магазины', shop: 'Магазин', aboutUs: 'О нас', sell: 'Продавать', account: 'Аккаунт', wishlist: 'Избранное', orders: 'Заказы', marketplaceNews: 'Новости рынка', articles: 'Статьи', about: 'О компании', contact: 'Контакты', support: 'Поддержка', settings: 'Настройки', loginRegister: 'Войти / Регистрация', search: 'Поиск', searchProducts: 'Поиск товаров, категорий...', searchProductsBrands: 'Поиск товаров, брендов, категорий…', adminDashboard: 'Панель администратора', sellerDashboard: 'Панель продавца', advertise: 'Реклама на Reliable', loadingReliable: 'Загрузка Reliable', quickLinks: 'Быстрые ссылки', products: 'Товары', contactUs: 'Связаться с нами', deliveryInformation: 'Информация о доставке', policies: 'Правила', privacyPolicy: 'Политика конфиденциальности', terms: 'Условия и положения', returns: 'Политика возврата и возмещения', premiumMarketplace: 'Премиальный маркетплейс', allRightsReserved: 'Все права защищены.', searchStores: 'Поиск магазинов, категорий или мест', loadingStores: 'Загрузка магазинов...', noResults: 'Ничего не найдено', addToCart: 'В корзину', outOfStock: 'Нет в наличии', checkout: 'Оформление заказа' },
  ja: { language: '言語', home: 'ホーム', categories: 'カテゴリー', ourCategories: 'カテゴリー一覧', deals: 'お得情報', startSelling: '販売を始める', stores: 'ストア', shop: 'ショップ', aboutUs: '私たちについて', sell: '販売する', account: 'アカウント', wishlist: 'お気に入り', orders: '注文', marketplaceNews: 'マーケットニュース', articles: '記事', about: '概要', contact: 'お問い合わせ', support: 'サポート', settings: '設定', loginRegister: 'ログイン / 登録', search: '検索', searchProducts: '商品、カテゴリーを検索...', searchProductsBrands: '商品、ブランド、カテゴリーを検索…', adminDashboard: '管理者ダッシュボード', sellerDashboard: '販売者ダッシュボード', advertise: 'Reliableに広告を掲載', loadingReliable: 'Reliableを読み込み中', quickLinks: 'クイックリンク', products: '商品', contactUs: 'お問い合わせ', deliveryInformation: '配送情報', policies: 'ポリシー', privacyPolicy: 'プライバシーポリシー', terms: '利用規約', returns: '返品・返金ポリシー', premiumMarketplace: 'プレミアムマーケットプレイス', allRightsReserved: '無断転載を禁じます。', searchStores: 'ストア、カテゴリー、場所を検索', loadingStores: 'ストアを読み込み中...', noResults: '結果がありません', addToCart: 'カートに追加', outOfStock: '在庫切れ', checkout: 'チェックアウト' },
  ko: { language: '언어', home: '홈', categories: '카테고리', ourCategories: '카테고리 보기', deals: '할인', startSelling: '판매 시작', stores: '스토어', shop: '쇼핑', aboutUs: '회사 소개', sell: '판매하기', account: '계정', wishlist: '찜 목록', orders: '주문', marketplaceNews: '마켓 뉴스', articles: '기사', about: '소개', contact: '문의', support: '지원', settings: '설정', loginRegister: '로그인 / 가입', search: '검색', searchProducts: '상품, 카테고리 검색...', searchProductsBrands: '상품, 브랜드, 카테고리 검색…', adminDashboard: '관리자 대시보드', sellerDashboard: '판매자 대시보드', advertise: 'Reliable에 광고하기', loadingReliable: 'Reliable 로드 중', quickLinks: '빠른 링크', products: '상품', contactUs: '문의하기', deliveryInformation: '배송 정보', policies: '정책', privacyPolicy: '개인정보 처리방침', terms: '이용약관', returns: '반품 및 환불 정책', premiumMarketplace: '프리미엄 마켓플레이스', allRightsReserved: '모든 권리 보유.', searchStores: '스토어, 카테고리 또는 위치 검색', loadingStores: '스토어 로드 중...', noResults: '결과 없음', addToCart: '장바구니에 추가', outOfStock: '품절', checkout: '결제' },
  de: { language: 'Sprache', home: 'Startseite', categories: 'Kategorien', ourCategories: 'Unsere Kategorien', deals: 'Angebote', startSelling: 'Verkaufen starten', stores: 'Shops', shop: 'Shop', aboutUs: 'Über uns', sell: 'Verkaufen', account: 'Konto', wishlist: 'Wunschliste', orders: 'Bestellungen', marketplaceNews: 'Marktplatz-News', articles: 'Artikel', about: 'Über', contact: 'Kontakt', support: 'Hilfe', settings: 'Einstellungen', loginRegister: 'Anmelden / Registrieren', search: 'Suchen', searchProducts: 'Produkte, Kategorien suchen...', searchProductsBrands: 'Produkte, Marken, Kategorien suchen…', adminDashboard: 'Admin-Dashboard', sellerDashboard: 'Verkäufer-Dashboard', advertise: 'Auf Reliable werben', loadingReliable: 'Reliable wird geladen', quickLinks: 'Schnelllinks', products: 'Produkte', contactUs: 'Kontaktieren Sie uns', deliveryInformation: 'Lieferinformationen', policies: 'Richtlinien', privacyPolicy: 'Datenschutzrichtlinie', terms: 'Allgemeine Geschäftsbedingungen', returns: 'Rückgabe- und Erstattungsrichtlinie', premiumMarketplace: 'Premium-Marktplatz', allRightsReserved: 'Alle Rechte vorbehalten.', searchStores: 'Shops, Kategorien oder Orte suchen', loadingStores: 'Shops werden geladen...', noResults: 'Keine Ergebnisse', addToCart: 'In den Warenkorb', outOfStock: 'Nicht vorrätig', checkout: 'Kasse' },
  it: { language: 'Lingua', home: 'Home', categories: 'Categorie', ourCategories: 'Le nostre categorie', deals: 'Offerte', startSelling: 'Inizia a vendere', stores: 'Negozi', shop: 'Acquista', aboutUs: 'Chi siamo', sell: 'Vendi', account: 'Account', wishlist: 'Lista desideri', orders: 'Ordini', marketplaceNews: 'Notizie del marketplace', articles: 'Articoli', about: 'Informazioni', contact: 'Contatti', support: 'Assistenza', settings: 'Impostazioni', loginRegister: 'Accedi / Registrati', search: 'Cerca', searchProducts: 'Cerca prodotti, categorie...', searchProductsBrands: 'Cerca prodotti, marchi, categorie…', adminDashboard: 'Dashboard amministratore', sellerDashboard: 'Dashboard venditore', advertise: 'Fai pubblicità su Reliable', loadingReliable: 'Caricamento di Reliable', quickLinks: 'Link rapidi', products: 'Prodotti', contactUs: 'Contattaci', deliveryInformation: 'Informazioni sulla consegna', policies: 'Politiche', privacyPolicy: 'Privacy', terms: 'Termini e condizioni', returns: 'Politica di reso e rimborso', premiumMarketplace: 'Marketplace premium', allRightsReserved: 'Tutti i diritti riservati.', searchStores: 'Cerca negozi, categorie o luoghi', loadingStores: 'Caricamento negozi...', noResults: 'Nessun risultato', addToCart: 'Aggiungi al carrello', outOfStock: 'Esaurito', checkout: 'Checkout' },
  tr: { language: 'Dil', home: 'Ana Sayfa', categories: 'Kategoriler', ourCategories: 'Kategorilerimiz', deals: 'Fırsatlar', startSelling: 'Satışa başlayın', stores: 'Mağazalar', shop: 'Mağaza', aboutUs: 'Hakkımızda', sell: 'Satış yap', account: 'Hesap', wishlist: 'İstek listesi', orders: 'Siparişler', marketplaceNews: 'Pazar haberleri', articles: 'Makaleler', about: 'Hakkında', contact: 'İletişim', support: 'Destek', settings: 'Ayarlar', loginRegister: 'Giriş / Kayıt', search: 'Ara', searchProducts: 'Ürün, kategori ara...', searchProductsBrands: 'Ürün, marka, kategori ara…', adminDashboard: 'Yönetici paneli', sellerDashboard: 'Satıcı paneli', advertise: "Reliable'da reklam ver", loadingReliable: 'Reliable yükleniyor', quickLinks: 'Hızlı bağlantılar', products: 'Ürünler', contactUs: 'Bize ulaşın', deliveryInformation: 'Teslimat bilgileri', policies: 'Politikalar', privacyPolicy: 'Gizlilik politikası', terms: 'Şartlar ve koşullar', returns: 'İade ve geri ödeme politikası', premiumMarketplace: 'Premium pazar yeri', allRightsReserved: 'Tüm hakları saklıdır.', searchStores: 'Mağaza, kategori veya konum ara', loadingStores: 'Mağazalar yükleniyor...', noResults: 'Sonuç bulunamadı', addToCart: 'Sepete ekle', outOfStock: 'Stokta yok', checkout: 'Ödeme' },
  vi: { language: 'Ngôn ngữ', home: 'Trang chủ', categories: 'Danh mục', ourCategories: 'Danh mục của chúng tôi', deals: 'Ưu đãi', startSelling: 'Bắt đầu bán', stores: 'Cửa hàng', shop: 'Mua sắm', aboutUs: 'Về chúng tôi', sell: 'Bán hàng', account: 'Tài khoản', wishlist: 'Danh sách yêu thích', orders: 'Đơn hàng', marketplaceNews: 'Tin thị trường', articles: 'Bài viết', about: 'Giới thiệu', contact: 'Liên hệ', support: 'Hỗ trợ', settings: 'Cài đặt', loginRegister: 'Đăng nhập / Đăng ký', search: 'Tìm kiếm', searchProducts: 'Tìm sản phẩm, danh mục...', searchProductsBrands: 'Tìm sản phẩm, thương hiệu, danh mục…', adminDashboard: 'Bảng quản trị', sellerDashboard: 'Bảng người bán', advertise: 'Quảng cáo trên Reliable', loadingReliable: 'Đang tải Reliable', quickLinks: 'Liên kết nhanh', products: 'Sản phẩm', contactUs: 'Liên hệ chúng tôi', deliveryInformation: 'Thông tin giao hàng', policies: 'Chính sách', privacyPolicy: 'Chính sách bảo mật', terms: 'Điều khoản và điều kiện', returns: 'Chính sách đổi trả và hoàn tiền', premiumMarketplace: 'Thị trường cao cấp', allRightsReserved: 'Đã đăng ký bản quyền.', searchStores: 'Tìm cửa hàng, danh mục hoặc địa điểm', loadingStores: 'Đang tải cửa hàng...', noResults: 'Không tìm thấy kết quả', addToCart: 'Thêm vào giỏ', outOfStock: 'Hết hàng', checkout: 'Thanh toán' },
  id: { language: 'Bahasa', home: 'Beranda', categories: 'Kategori', ourCategories: 'Kategori Kami', deals: 'Penawaran', startSelling: 'Mulai berjualan', stores: 'Toko', shop: 'Belanja', aboutUs: 'Tentang kami', sell: 'Jual', account: 'Akun', wishlist: 'Daftar keinginan', orders: 'Pesanan', marketplaceNews: 'Berita marketplace', articles: 'Artikel', about: 'Tentang', contact: 'Kontak', support: 'Bantuan', settings: 'Pengaturan', loginRegister: 'Masuk / Daftar', search: 'Cari', searchProducts: 'Cari produk, kategori...', searchProductsBrands: 'Cari produk, merek, kategori…', adminDashboard: 'Dasbor admin', sellerDashboard: 'Dasbor penjual', advertise: 'Beriklan di Reliable', loadingReliable: 'Memuat Reliable', quickLinks: 'Tautan cepat', products: 'Produk', contactUs: 'Hubungi kami', deliveryInformation: 'Informasi pengiriman', policies: 'Kebijakan', privacyPolicy: 'Kebijakan privasi', terms: 'Syarat dan ketentuan', returns: 'Kebijakan pengembalian dan pengembalian dana', premiumMarketplace: 'Marketplace premium', allRightsReserved: 'Hak cipta dilindungi.', searchStores: 'Cari toko, kategori, atau lokasi', loadingStores: 'Memuat toko...', noResults: 'Tidak ada hasil', addToCart: 'Tambahkan ke keranjang', outOfStock: 'Stok habis', checkout: 'Checkout' },
  nl: { language: 'Taal', home: 'Home', categories: 'Categorieën', ourCategories: 'Onze categorieën', deals: 'Aanbiedingen', startSelling: 'Begin met verkopen', stores: 'Winkels', shop: 'Shop', aboutUs: 'Over ons', sell: 'Verkopen', account: 'Account', wishlist: 'Verlanglijst', orders: 'Bestellingen', marketplaceNews: 'Marktplaatsnieuws', articles: 'Artikelen', about: 'Over', contact: 'Contact', support: 'Ondersteuning', settings: 'Instellingen', loginRegister: 'Inloggen / Registreren', search: 'Zoeken', searchProducts: 'Zoek producten, categorieën...', searchProductsBrands: 'Zoek producten, merken, categorieën…', adminDashboard: 'Beheerdersdashboard', sellerDashboard: 'Verkopersdashboard', advertise: 'Adverteren op Reliable', loadingReliable: 'Reliable laden', quickLinks: 'Snelle links', products: 'Producten', contactUs: 'Neem contact op', deliveryInformation: 'Bezorginformatie', policies: 'Beleid', privacyPolicy: 'Privacybeleid', terms: 'Algemene voorwaarden', returns: 'Retour- en terugbetalingsbeleid', premiumMarketplace: 'Premium marktplaats', allRightsReserved: 'Alle rechten voorbehouden.', searchStores: 'Zoek winkels, categorieën of locaties', loadingStores: 'Winkels laden...', noResults: 'Geen resultaten', addToCart: 'Toevoegen aan winkelwagen', outOfStock: 'Niet op voorraad', checkout: 'Afrekenen' },
  pl: { language: 'Język', home: 'Strona główna', categories: 'Kategorie', ourCategories: 'Nasze kategorie', deals: 'Promocje', startSelling: 'Zacznij sprzedawać', stores: 'Sklepy', shop: 'Sklep', aboutUs: 'O nas', sell: 'Sprzedawaj', account: 'Konto', wishlist: 'Lista życzeń', orders: 'Zamówienia', marketplaceNews: 'Wiadomości marketplace', articles: 'Artykuły', about: 'O nas', contact: 'Kontakt', support: 'Pomoc', settings: 'Ustawienia', loginRegister: 'Logowanie / Rejestracja', search: 'Szukaj', searchProducts: 'Szukaj produktów, kategorii...', searchProductsBrands: 'Szukaj produktów, marek, kategorii…', adminDashboard: 'Panel administratora', sellerDashboard: 'Panel sprzedawcy', advertise: 'Reklamuj się na Reliable', loadingReliable: 'Ładowanie Reliable', quickLinks: 'Szybkie linki', products: 'Produkty', contactUs: 'Skontaktuj się', deliveryInformation: 'Informacje o dostawie', policies: 'Zasady', privacyPolicy: 'Polityka prywatności', terms: 'Regulamin', returns: 'Polityka zwrotów i refundacji', premiumMarketplace: 'Platforma premium', allRightsReserved: 'Wszelkie prawa zastrzeżone.', searchStores: 'Szukaj sklepów, kategorii lub lokalizacji', loadingStores: 'Ładowanie sklepów...', noResults: 'Brak wyników', addToCart: 'Dodaj do koszyka', outOfStock: 'Brak w magazynie', checkout: 'Do kasy' },
  sw: { language: 'Lugha', home: 'Nyumbani', categories: 'Aina', ourCategories: 'Aina Zetu', deals: 'Ofa', startSelling: 'Anza kuuza', stores: 'Maduka', shop: 'Nunua', aboutUs: 'Kuhusu sisi', sell: 'Uza', account: 'Akaunti', wishlist: 'Orodha ya matamanio', orders: 'Maagizo', marketplaceNews: 'Habari za soko', articles: 'Makala', about: 'Kuhusu', contact: 'Mawasiliano', support: 'Msaada', settings: 'Mipangilio', loginRegister: 'Ingia / Jisajili', search: 'Tafuta', searchProducts: 'Tafuta bidhaa, aina...', searchProductsBrands: 'Tafuta bidhaa, chapa, aina…', adminDashboard: 'Dashibodi ya msimamizi', sellerDashboard: 'Dashibodi ya muuzaji', advertise: 'Tangaza kwenye Reliable', loadingReliable: 'Reliable inapakia', quickLinks: 'Viungo vya haraka', products: 'Bidhaa', contactUs: 'Wasiliana nasi', deliveryInformation: 'Maelezo ya uwasilishaji', policies: 'Sera', privacyPolicy: 'Sera ya faragha', terms: 'Masharti', returns: 'Sera ya kurejesha na kurefund', premiumMarketplace: 'Soko la kiwango cha juu', allRightsReserved: 'Haki zote zimehifadhiwa.', searchStores: 'Tafuta maduka, aina au maeneo', loadingStores: 'Maduka yanapakia...', noResults: 'Hakuna matokeo', addToCart: 'Ongeza kwenye kikapu', outOfStock: 'Imeisha', checkout: 'Malipo' },
  ha: { language: 'Harshe', home: 'Gida', categories: 'Rukuni', ourCategories: 'Rukuninmu', deals: 'Rangwame', startSelling: 'Fara sayarwa', stores: 'Shaguna', shop: 'Siyayya', aboutUs: 'Game da mu', sell: 'Sayar', account: 'Asusu', wishlist: 'Jerin buri', orders: 'Oda', marketplaceNews: 'Labaran kasuwa', articles: 'Labarai', about: 'Game da', contact: 'Tuntuɓe', support: 'Taimako', settings: 'Saituna', loginRegister: 'Shiga / Yi rajista', search: 'Bincika', searchProducts: 'Binciki kaya, rukuni...', searchProductsBrands: 'Binciki kaya, alama, rukuni…', adminDashboard: 'Allon mai gudanarwa', sellerDashboard: 'Allon mai sayarwa', advertise: 'Tallata a Reliable', loadingReliable: 'Ana loda Reliable', quickLinks: 'Hanyoyi masu sauri', products: 'Kayayyaki', contactUs: 'Tuntuɓe mu', deliveryInformation: 'Bayanin isarwa', policies: 'Manufofi', privacyPolicy: 'Manufar sirri', terms: 'Sharuɗɗa da ƙaidoji', returns: 'Manufar mayarwa da kuɗi', premiumMarketplace: 'Kasuwa mai daraja', allRightsReserved: 'An kiyaye duk haƙƙoƙi.', searchStores: 'Binciki shaguna, rukuni ko wurare', loadingStores: 'Ana loda shaguna...', noResults: 'Ba a sami sakamako ba', addToCart: 'Ƙara zuwa kwando', outOfStock: 'Babu kaya', checkout: 'Biya' },
  mg: { language: 'Fiteny', home: 'Fandraisana', categories: 'Sokajy', ourCategories: 'Ireo sokajintsika', deals: 'Tolotra', startSelling: 'Manomboka mivarotra', stores: 'Fivarotana', shop: 'Miantsena', aboutUs: 'Momba anay', sell: 'Mivarotra', account: 'Kaonty', wishlist: 'Lisitra tiana', orders: 'Kaomandy', marketplaceNews: 'Vaovaon’ny tsena', articles: 'Lahatsoratra', about: 'Momba', contact: 'Fifandraisana', support: 'Fanampiana', settings: 'Fikirana', loginRegister: 'Hiditra / Hisoratra anarana', search: 'Hikaroka', searchProducts: 'Karohy ny vokatra sy sokajy...', searchProductsBrands: 'Karohy ny vokatra, marika, sokajy…', adminDashboard: 'Tabilao mpitantana', sellerDashboard: 'Tabilao mpivarotra', advertise: 'Manaova dokambarotra ao amin’ny Reliable', loadingReliable: 'Mampiditra Reliable', quickLinks: 'Rohy haingana', products: 'Vokatra', contactUs: 'Mifandraisa aminay', deliveryInformation: 'Mombamomba ny fanaterana', policies: 'Politika', privacyPolicy: 'Politika momba ny tsiambaratelo', terms: 'Fepetra sy fitsipika', returns: 'Politika famerenana sy famerenam-bola', premiumMarketplace: 'Tsena premium', allRightsReserved: 'Voatahiry ny zo rehetra.', searchStores: 'Karohy ny fivarotana, sokajy na toerana', loadingStores: 'Mampiditra fivarotana...', noResults: 'Tsy nahita valiny', addToCart: 'Ampio ao anaty sarety', outOfStock: 'Lany tahiry', checkout: 'Fandoavana' },
}

const customerTranslations: Partial<Record<LanguageCode, TranslationMap>> = {
  zh: { viewDetails: '查看详情', sponsored: '赞助', marketplacePick: '市场精选', deliveryAvailable: '提供配送', brand: '品牌', newProduct: '新品', reviews: '条评价', productNotFound: '未找到产品', backToProducts: '返回产品', soldBy: '卖家', description: '描述', selectSizes: '选择尺寸（可多选）', quantity: '数量', chatWithSeller: '与卖家聊天', removeFromWishlist: '从愿望清单移除', addToWishlist: '加入愿望清单', noMediaAvailable: '暂无媒体', inStock: '有货', shoppingCart: '购物车', closeCart: '关闭购物车', emptyCart: '购物车为空', continueShopping: '继续购物', cartSummary: '购物车摘要', subtotal: '小计', item: '件', items: '件', remove: '移除', proceedToCheckout: '去结账', emptyCartAction: '清空购物车', browseProducts: '浏览产品', createAccountToContinue: '创建客户账户以继续', createCustomerAccount: '创建客户账户', login: '登录', fullName: '姓名', emailAddress: '电子邮件地址', phoneNumber: '电话号码', deliveryAddress: '配送地址', city: '城市', region: '地区', deliveryMethod: '配送方式', additionalNotes: '附加备注', processing: '处理中...', proceedToPayment: '继续支付', needHelp: '需要订单帮助？', callUs: '联系我们', processingPayment: '正在处理付款', verifyPayment: '验证付款', verifyingPayment: '正在验证付款', orderSummary: '订单摘要', deliveryFee: '配送费', total: '总计' },
  es: { viewDetails: 'Ver detalles', sponsored: 'Patrocinado', marketplacePick: 'Selección del marketplace', deliveryAvailable: 'Envío disponible', brand: 'Marca', newProduct: 'Nuevo', reviews: 'reseñas', productNotFound: 'Producto no encontrado', backToProducts: 'Volver a productos', soldBy: 'Vendido por', description: 'Descripción', selectSizes: 'Seleccionar tallas (se permiten varias)', quantity: 'Cantidad', chatWithSeller: 'Chatear con el vendedor', removeFromWishlist: 'Eliminar de favoritos', addToWishlist: 'Añadir a favoritos', noMediaAvailable: 'Sin contenido multimedia', inStock: 'En stock', shoppingCart: 'Carrito', closeCart: 'Cerrar carrito', emptyCart: 'Tu carrito está vacío', continueShopping: 'Continuar comprando', cartSummary: 'Resumen del carrito', subtotal: 'Subtotal', item: 'artículo', items: 'artículos', remove: 'Eliminar', proceedToCheckout: 'Proceder al pago', emptyCartAction: 'Vaciar carrito', browseProducts: 'Ver productos', createAccountToContinue: 'Crea una cuenta de cliente para continuar', createCustomerAccount: 'Crear cuenta de cliente', login: 'Iniciar sesión', fullName: 'Nombre completo', emailAddress: 'Correo electrónico', phoneNumber: 'Teléfono', deliveryAddress: 'Dirección de entrega', city: 'Ciudad', region: 'Región', deliveryMethod: 'Método de entrega', additionalNotes: 'Notas adicionales', processing: 'Procesando...', proceedToPayment: 'Proceder al pago', needHelp: '¿Necesitas ayuda con tu pedido?', callUs: 'Llámanos', processingPayment: 'Procesando el pago', verifyPayment: 'Verificar pago', verifyingPayment: 'Verificando el pago', orderSummary: 'Resumen del pedido', deliveryFee: 'Envío', total: 'Total' },
  fr: { viewDetails: 'Voir les détails', sponsored: 'Sponsorisé', marketplacePick: 'Sélection du marketplace', deliveryAvailable: 'Livraison disponible', brand: 'Marque', newProduct: 'Nouveau', reviews: 'avis', productNotFound: 'Produit introuvable', backToProducts: 'Retour aux produits', soldBy: 'Vendu par', description: 'Description', selectSizes: 'Choisir les tailles (plusieurs possibles)', quantity: 'Quantité', chatWithSeller: 'Discuter avec le vendeur', removeFromWishlist: 'Retirer des favoris', addToWishlist: 'Ajouter aux favoris', noMediaAvailable: 'Aucun média disponible', inStock: 'En stock', shoppingCart: 'Panier', closeCart: 'Fermer le panier', emptyCart: 'Votre panier est vide', continueShopping: 'Continuer les achats', cartSummary: 'Résumé du panier', subtotal: 'Sous-total', item: 'article', items: 'articles', remove: 'Supprimer', proceedToCheckout: 'Passer à la caisse', emptyCartAction: 'Vider le panier', browseProducts: 'Parcourir les produits', createAccountToContinue: 'Créez un compte client pour continuer', createCustomerAccount: 'Créer un compte client', login: 'Connexion', fullName: 'Nom complet', emailAddress: 'Adresse e-mail', phoneNumber: 'Numéro de téléphone', deliveryAddress: 'Adresse de livraison', city: 'Ville', region: 'Région', deliveryMethod: 'Mode de livraison', additionalNotes: 'Notes supplémentaires', processing: 'Traitement...', proceedToPayment: 'Procéder au paiement', needHelp: 'Besoin d’aide pour votre commande ?', callUs: 'Appelez-nous', processingPayment: 'Paiement en cours', verifyPayment: 'Vérifier le paiement', verifyingPayment: 'Vérification du paiement', orderSummary: 'Résumé de la commande', deliveryFee: 'Frais de livraison', total: 'Total' },
  ar: { viewDetails: 'عرض التفاصيل', sponsored: 'برعاية', marketplacePick: 'اختيار السوق', deliveryAvailable: 'التوصيل متاح', brand: 'العلامة التجارية', newProduct: 'جديد', reviews: 'تقييمات', productNotFound: 'المنتج غير موجود', backToProducts: 'العودة إلى المنتجات', soldBy: 'يباع بواسطة', description: 'الوصف', selectSizes: 'اختر المقاسات (يمكن اختيار أكثر من مقاس)', quantity: 'الكمية', chatWithSeller: 'محادثة مع البائع', removeFromWishlist: 'إزالة من قائمة الرغبات', addToWishlist: 'إضافة إلى قائمة الرغبات', noMediaAvailable: 'لا توجد وسائط', inStock: 'متوفر', shoppingCart: 'سلة التسوق', closeCart: 'إغلاق السلة', emptyCart: 'سلة التسوق فارغة', continueShopping: 'متابعة التسوق', cartSummary: 'ملخص السلة', subtotal: 'المجموع الفرعي', item: 'عنصر', items: 'عناصر', remove: 'إزالة', proceedToCheckout: 'المتابعة إلى الدفع', emptyCartAction: 'إفراغ السلة', browseProducts: 'تصفح المنتجات', createAccountToContinue: 'أنشئ حساب عميل للمتابعة', createCustomerAccount: 'إنشاء حساب عميل', login: 'تسجيل الدخول', fullName: 'الاسم الكامل', emailAddress: 'البريد الإلكتروني', phoneNumber: 'رقم الهاتف', deliveryAddress: 'عنوان التوصيل', city: 'المدينة', region: 'المنطقة', deliveryMethod: 'طريقة التوصيل', additionalNotes: 'ملاحظات إضافية', processing: 'جارٍ المعالجة...', proceedToPayment: 'المتابعة إلى الدفع', needHelp: 'هل تحتاج مساعدة بشأن طلبك؟', callUs: 'اتصل بنا', processingPayment: 'جارٍ معالجة الدفع', verifyPayment: 'تحقق من الدفع', verifyingPayment: 'جارٍ التحقق من الدفع', orderSummary: 'ملخص الطلب', deliveryFee: 'رسوم التوصيل', total: 'الإجمالي' },
  ja: { viewDetails: '詳細を見る', sponsored: 'スポンサー', marketplacePick: 'マーケットプレイスおすすめ', deliveryAvailable: '配送可能', brand: 'ブランド', newProduct: '新着', reviews: '件のレビュー', productNotFound: '商品が見つかりません', backToProducts: '商品一覧に戻る', soldBy: '販売者', description: '説明', selectSizes: 'サイズを選択（複数可）', quantity: '数量', chatWithSeller: '販売者にチャット', removeFromWishlist: 'お気に入りから削除', addToWishlist: 'お気に入りに追加', noMediaAvailable: 'メディアなし', inStock: '在庫あり', shoppingCart: 'ショッピングカート', closeCart: 'カートを閉じる', emptyCart: 'カートは空です', continueShopping: '買い物を続ける', cartSummary: 'カート概要', subtotal: '小計', item: '点', items: '点', remove: '削除', proceedToCheckout: 'チェックアウトへ', emptyCartAction: 'カートを空にする', browseProducts: '商品を見る', createAccountToContinue: '続けるには顧客アカウントを作成してください', createCustomerAccount: '顧客アカウントを作成', login: 'ログイン', fullName: '氏名', emailAddress: 'メールアドレス', phoneNumber: '電話番号', deliveryAddress: '配送先住所', city: '市区町村', region: '地域', deliveryMethod: '配送方法', additionalNotes: '追加メモ', processing: '処理中...', proceedToPayment: '支払いへ進む', needHelp: '注文についてサポートが必要ですか？', callUs: 'お問い合わせ', processingPayment: '支払いを処理中', verifyPayment: '支払いを確認', verifyingPayment: '支払いを確認中', orderSummary: '注文概要', deliveryFee: '配送料', total: '合計' },
  ha: { viewDetails: 'Duba bayanai', sponsored: 'Tallace', marketplacePick: 'Zaɓin kasuwa', deliveryAvailable: 'Ana iya kaiwa', brand: 'Alama', newProduct: 'Sabo', reviews: 'bita', productNotFound: 'Ba a sami kaya ba', backToProducts: 'Koma kaya', soldBy: 'Mai sayarwa', description: 'Bayani', selectSizes: 'Zaɓi girma (ana iya da yawa)', quantity: 'Yawa', chatWithSeller: 'Yi magana da mai sayarwa', removeFromWishlist: 'Cire daga jerin buri', addToWishlist: 'Ƙara zuwa jerin buri', noMediaAvailable: 'Babu hoto ko bidiyo', inStock: 'Akwai', shoppingCart: 'Kwandon sayayya', closeCart: 'Rufe kwando', emptyCart: 'Kwandonka babu komai', continueShopping: 'Ci gaba da sayayya', cartSummary: 'Taƙaitaccen kwando', subtotal: 'Jimillar farko', item: 'kaya', items: 'kaya', remove: 'Cire', proceedToCheckout: 'Ci gaba zuwa biya', emptyCartAction: 'Share kwando', browseProducts: 'Duba kaya', createAccountToContinue: 'Ƙirƙiri asusun abokin ciniki don ci gaba', createCustomerAccount: 'Ƙirƙiri asusun abokin ciniki', login: 'Shiga', fullName: 'Cikakken suna', emailAddress: 'Adireshin imel', phoneNumber: 'Lambar waya', deliveryAddress: 'Adireshin kai kaya', city: 'Birni', region: 'Yanki', deliveryMethod: 'Hanyar kai kaya', additionalNotes: 'Ƙarin bayanai', processing: 'Ana sarrafawa...', proceedToPayment: 'Ci gaba zuwa biya', needHelp: 'Kana buƙatar taimako da oda?', callUs: 'Kira mu', processingPayment: 'Ana sarrafa biya', verifyPayment: 'Tabbatar da biya', verifyingPayment: 'Ana tabbatar da biya', orderSummary: 'Taƙaitaccen oda', deliveryFee: 'Kuɗin kai kaya', total: 'Jimilla' },
}

interface I18nContextValue { language: LanguageCode; setLanguage: (language: LanguageCode) => void; t: (key: TranslationKey) => string; direction: 'ltr' | 'rtl' }
const I18nContext = createContext<I18nContextValue | null>(null)

const getInitialLanguage = (): LanguageCode => {
  const saved = localStorage.getItem(LANGUAGE_STORAGE_KEY) as LanguageCode | null
  if (saved && LANGUAGES.some(({ code }) => code === saved)) return saved
  const browser = navigator.language?.split('-')[0] as LanguageCode
  return LANGUAGES.some(({ code }) => code === browser) ? browser : 'en'
}

export function I18nProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<LanguageCode>(getInitialLanguage)
  const metadata = LANGUAGES.find(({ code }) => code === language) || LANGUAGES[0]
  const setLanguage = (next: LanguageCode) => { setLanguageState(next); localStorage.setItem(LANGUAGE_STORAGE_KEY, next) }
  useEffect(() => { document.documentElement.lang = language; document.documentElement.dir = metadata.dir }, [language, metadata.dir])
  const value = useMemo<I18nContextValue>(() => ({ language, setLanguage, direction: metadata.dir, t: (key) => customerTranslations[language]?.[key] || translations[language][key] || translations.en[key] || key }), [language, metadata.dir])
  return <I18nContext.Provider value={value}>{children}</I18nContext.Provider>
}

export const useI18n = () => {
  const context = useContext(I18nContext)
  if (!context) throw new Error('useI18n must be used inside I18nProvider')
  return context
}
