import { useEffect, useState } from 'react'
import { useAuth } from '../context/AuthContext'
import { supabase } from '../supabaseClient'
import { initializePayment, confirmSellerPromotion, generatePaymentReference } from '../services/paystackService'
import { getAllProducts } from '../services/productService'
import type { Product } from '../types'
import './SellerPromotions.css'

type Plan = { id: string; code: 'FEATURED_PRODUCT' | 'FEATURED_STORE'; name: string; price_minor: number; currency: string; duration_days: number; placement: string; is_active: boolean }
export default function SellerPromotions({ businessIds }: { businessIds: string[] }) {
  const { user, session } = useAuth(); const [plans, setPlans] = useState<Plan[]>([]); const [products, setProducts] = useState<Product[]>([]); const [type, setType] = useState<Plan['code']>('FEATURED_PRODUCT'); const [productId, setProductId] = useState(''); const [planId, setPlanId] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false)
  const businessId = businessIds[0]
  useEffect(() => { if (!supabase || !businessId) return; void (async () => { const [{ data: plansData }, productsData] = await Promise.all([supabase.from('promotion_plans').select('*').eq('is_active', true).order('price_minor'), getAllProducts(businessId)]); setPlans((plansData || []) as Plan[]); setProducts((productsData || []) as Product[]) })() }, [businessId])
  useEffect(() => { const ref = new URLSearchParams(window.location.search).get('reference') || new URLSearchParams(window.location.search).get('trxref'); const saved = localStorage.getItem('reliable_pending_promotion'); if (!ref || !saved || !session?.access_token) return; const pending = JSON.parse(saved) as { promotion_id: string; reference: string }; if (pending.reference !== ref) return; void (async () => { setBusy(true); try { await confirmSellerPromotion({ promotion_id: pending.promotion_id, reference: ref }, session.access_token); localStorage.removeItem('reliable_pending_promotion'); setMessage('Payment verified. Your promotion is now active.'); window.history.replaceState({}, '', window.location.pathname) } catch (error) { setMessage(error instanceof Error ? error.message : 'Promotion payment could not be confirmed.') } finally { setBusy(false) } })() }, [session?.access_token])
  const selectedPlan = plans.find(p => p.id === planId)
  const startPayment = async () => { if (!user?.email || !session?.access_token || !businessId || !selectedPlan) return setMessage('Choose an active promotion plan first.'); if (type === 'FEATURED_PRODUCT' && !productId) return setMessage('Choose a product to promote.'); setBusy(true); setMessage(''); try { const reference = generatePaymentReference(); const result = await initializePayment({ email: user.email, amount: selectedPlan.price_minor, currency: selectedPlan.currency, reference, callback_url: `${window.location.origin}/admin`, metadata: { type: 'seller_promotion', business_id: businessId, product_id: type === 'FEATURED_PRODUCT' ? productId : null, plan_id: selectedPlan.id, promotion_type: type } }, session.access_token); const promotionId = (result.data as typeof result.data & { promotion_id: string }).promotion_id; localStorage.setItem('reliable_pending_promotion', JSON.stringify({ promotion_id: promotionId, reference })); window.location.href = result.data.authorization_url } catch (error) { setMessage(error instanceof Error ? error.message : 'Could not start promotion payment.') } finally { setBusy(false) } }
  return <section className="seller-promotions animate-fade-in"><div className="section-title-wrapper"><h2 className="section-title">Promote Your Store or Product</h2><p>Paid placements are clearly marked FEATURED and activate only after Paystack verification.</p></div><div className="seller-promotion-card"><div className="seller-promotion-grid"><select value={type} onChange={e => { setType(e.target.value as Plan['code']); setPlanId('') }}><option value="FEATURED_PRODUCT">Featured Product</option><option value="FEATURED_STORE">Featured Store</option></select>{type === 'FEATURED_PRODUCT' && <select value={productId} onChange={e => setProductId(e.target.value)}><option value="">Choose product</option>{products.map(p => <option key={p.id} value={p.id}>{p.name}</option>)}</select>}<select value={planId} onChange={e => setPlanId(e.target.value)}><option value="">Choose duration and price</option>{plans.filter(p => p.code === type).map(p => <option key={p.id} value={p.id}>{p.name} — {p.currency} {(p.price_minor / 100).toFixed(2)} / {p.duration_days} days</option>)}</select><button disabled={busy} onClick={() => void startPayment()}>{busy ? 'Processing…' : 'Pay with Paystack'}</button></div>{selectedPlan && <p className="seller-promotion-note">This placement runs for {selectedPlan.duration_days} days and expires automatically.</p>}{message && <p className="seller-promotion-message">{message}</p>}</div></section>
}
